baseURL = "https://apireference.aspose.com/drawing"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-NJMHSH"

[[deployment.targets]]
name = "Production"
URL = "s3://apireference.aspose.com/?prefix=drawing/&region=us-west-2"

