baseURL = "https://reference.aspose.com/pdf"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-NJMHSH"

[[deployment.targets]]
name = "Production"
URL = "s3://reference.aspose.com/?prefix=pdf/&region=us-west-2"
