baseURL: "https://reference2.aspose.com/cells/python-net/ru"
title: "Aspose API References"
contentDir: 'content/sites/aspose/cells-python-net/russian'  # Add this line
staticdir: 'content/sites/aspose/cells-python-net/static'
enableRobotsTXT: true
enableGitInfo: true
disableKinds: ["taxonomy", "taxonomyTerm", "page", "RSS"]

theme: ["api-theme"]

params:
  menu:
    ru: "aspose-ru"
  gtm:
    gtm_id: "GTM-NJMHSH"
  meta:
    msapplication_TileColor: "#2b5797"
    msapplication_config: "https://cms.admin.containerize.com/templates/asposecloud/images/browserconfig.xml"
    theme_color: "#ffffff"
    author: "Aspose"
  containerize:
    menu: "aspose-ru"
  copyright: "The Aspose Authors"
  privacy_policy: "https://policies.google.com/privacy"
  topbar_search_active: false
  logo_rel_link: ""
  title_404_page: "404 - Page Not Found | Aspose API References"
  images: ["images/Aspose-image-for-open-graph.jpg"]
  description: "Class Libraries & REST APIs for the developers to manipulate & process Files from Word, Excel, PowerPoint, Visio, PDF, CAD & several other categories in Web, Desktop or Mobile apps. Develop & deploy on Windows, Linux, MacOS & Android platforms."
  ui:
    sidebar_menu_compact: true
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: false
    footer_about_disable: false

defaultContentLang: 'ru'
languages:
  ru:
    contentDir: 'content/sites/aspose/cells-python-net/russian'
    languageName: 'Русский'
    languageCode: "ru"
    flag: "flag-ru"
    weight: 11

ignoreFiles: ["(?i:readme.md)", '\.spin$']

imaging:
  resampleFilter: "CatmullRom"
  quality: 75
  anchor: "smart"

markup:
  tableOfContents:
    endLevel: 2
    ordered: true
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true

deployment:
  matchers:
    - pattern: "^.+\\.(xml)$"
      contentType: "application/xml"
      gzip: true
      force: true
  targets:
    - name: "Production"
      URL: "s3://reference.aspose.com/?prefix=cells/python-net/ru/&region=us-west-2"
    - name: "Stage"
      URL: "s3://reference2.aspose.com/?prefix=cells/python-net/ru/&region=us-west-2"
