baseURL = "https://apireference.aspose.com/3d"

# Google Tag Manager settings
[params.gmt]
gmt_id = "GTM-NJMHSH"

[[deployment.targets]]
name = "Production"
URL = "s3://apireference.aspose.com/?prefix=3d/&region=us-west-2"

