name: All PUB Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-pub-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pub-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pub-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

