name: All FONT Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-font-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

