name: All CELLS-PYTHON-NET Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cells-python-net-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

