name: All CAD Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cad-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cad-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cad-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}
