name: All WORDS Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-words-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

