name: All CELLS-PYTHON-NET Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cells-python-net-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

