name: All OCR Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-ocr-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-greece-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-greece-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indonesian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indonesian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-japanese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-japanese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-korean-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-korean-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-netherlands-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-netherlands-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

