name: All OCR Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-ocr-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-greece-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-greece-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indonesian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indonesian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-japanese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-japanese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-korean-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-korean-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-netherlands-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-netherlands-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

