name: All GIS Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-gis-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-greece-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-greece-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-indian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-indian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-indonesian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-indonesian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-japanese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-japanese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-korean-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-korean-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-netherlands-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-netherlands-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

