name: All BARCODE Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-barcode-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-greece-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-greece-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indonesian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indonesian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-japanese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-japanese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-korean-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-korean-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-netherlands-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-netherlands-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

