name: All DIAGRAM Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-diagram-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-greece-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-greece-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-netherlands-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-netherlands-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

