name: All IMAGING Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-imaging-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

