name: All PDF Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-pdf-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-indonesian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-indonesian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-japanese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-japanese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-korean-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-korean-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-portuguese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-portuguese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

