name: All CAD Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cad-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cad-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cad-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cad-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}
