name: All FONT Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-font-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

