name: All PAGE Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-page-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-page-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-page-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

