name: All PDF Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-pdf-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-indonesian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-indonesian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-japanese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-japanese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-korean-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-korean-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-portuguese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-portuguese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

