name: All BARCODE Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-barcode-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-greece-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-greece-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indonesian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indonesian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-japanese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-japanese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-korean-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-korean-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-netherlands-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-netherlands-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

