name: All FONT Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-font-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-font-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-font-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

