name: All EMAIL Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-email-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-email-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-email-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-email-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-email-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-email-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

