name: All CELLS Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cells-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

