name: All TASKS Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-tasks-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-greece-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-greece-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-indian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-indian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-netherlands-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-netherlands-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tasks-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tasks-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

