name: All 3D Staging Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-3d-arabic-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-arabic-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-chinese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-chinese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-english-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-english-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-french-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-french-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-german-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-german-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-greece-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-greece-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-indian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-indian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-indonesian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-indonesian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-italian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-italian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-japanese-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-japanese-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-korean-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-korean-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-netherlands-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-netherlands-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-russian-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-russian-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-spanish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-spanish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-swedish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-swedish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-turkish-stage-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-turkish-stage-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

