name: All BARCODE Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-barcode-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

