name: All 3D Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-3d-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-3d-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-3d-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

