name: All IMAGING Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-imaging-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-imaging-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-imaging-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

