name: All FINANCE Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-finance-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-finance-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-finance-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

