name: All HTML Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-html-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-html-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-html-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

