name: All DRAWING Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-drawing-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-greece-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-greece-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-indian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-indian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-netherlands-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-netherlands-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

