name: All OCR Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-ocr-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-greece-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-greece-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-netherlands-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-netherlands-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-ocr-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-ocr-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

