name: All PDF Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-pdf-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-portuguese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-portuguese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-pdf-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-pdf-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

