name: All NOTE Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-note-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-note-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-note-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

