name: All CELLS-PYTHON-NET Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-cells-python-net-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-cells-python-net-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-cells-python-net-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

