name: All SVG Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-svg-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-svg-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-svg-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

