name: All BARCODE Production Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-barcode-arabic-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-arabic-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-chinese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-chinese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-english-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-english-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-french-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-french-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-german-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-german-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-greece-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-greece-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-indonesian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-indonesian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-italian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-italian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-japanese-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-japanese-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-korean-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-korean-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-netherlands-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-netherlands-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-russian-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-russian-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-spanish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-spanish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-swedish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-swedish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-barcode-turkish-production
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-barcode-turkish-production.yml
          token: ${{ secrets.REPO_TOKEN }}

