name: All WORDS Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-words-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

