name: All WORDS Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-words-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-words-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-words-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

