name: All DIAGRAM Staging Workflows (S3)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-diagram-arabic-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-arabic-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-chinese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-chinese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-english-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-english-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-french-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-french-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-german-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-german-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-greece-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-greece-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indonesian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indonesian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-italian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-italian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-japanese-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-japanese-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-korean-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-korean-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-netherlands-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-netherlands-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-russian-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-russian-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-spanish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-spanish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-swedish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-swedish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-turkish-stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-turkish-stage.yml
          token: ${{ secrets.REPO_TOKEN }}

