name: All GIS Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-gis-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-gis-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-gis-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

