name: All TEX Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-tex-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-tex-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-tex-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

