name: All OMR Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-omr-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-omr-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-omr-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

