name: All DRAWING Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-drawing-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-drawing-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-drawing-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

