name: All DIAGRAM Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-diagram-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-diagram-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-diagram-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

