name: All PSD Production Workflows (BunnyCDN)

on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-psd-arabic-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-arabic-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-chinese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-chinese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-english-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-english-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-french-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-french-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-german-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-german-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-greece-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-greece-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-indian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-indian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-indonesian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-indonesian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-italian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-italian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-japanese-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-japanese-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-korean-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-korean-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-netherlands-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-netherlands-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-russian-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-russian-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-spanish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-spanish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-swedish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-swedish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

      - name: Trigger build-psd-turkish-production-bunny
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-psd-turkish-production-bunny.yml
          token: ${{ secrets.REPO_TOKEN }}

