# This is a basic workflow to help you get started with Actions

name: apireference2.aspose.com(email)(Stage)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'content/sites/aspose/email/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: true  # Fetch Hugo themes
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod     
      - name: Checkout theme repo
        uses: actions/checkout@main
        with:
          repository: Aspose/api-theme
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: beta
          path: themes/api-theme      
      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.0'
          extended: true
      - name: Debug go.sum files
        run: |
          find . -name 'go.sum' | xargs -I {} stat {}          
      - name: Install Dependicies1
        run:  npm install -D --save autoprefixer
      - name: Install Dependicies2
        run:  npm install -D --save postcss-cli
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache    # <-- with hugo version v0.116.0 and above
          # path: /tmp/hugo_cache                 # <-- with hugo version < v0.116.0
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      # Also specifies the theme we want to use
      - name: Build
        run: hugo --configDir config/sites/aspose/email --environment staging --minify
        
      - name: Deploy apireference2.aspose.com(email)(Stage) to S3
        run: hugo --configDir config/sites/aspose/email --environment staging deploy --target "Stage" --maxDeletes 0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
      # Invalidate Cloudfront Home Page
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
          PATHS: /email/*
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
