name: Build PDF Italian Stage

on:
  repository_dispatch:
    types: [ build-pdf-italian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-pdf/Aspose.PDF-API-References"
      product_name: "pdf"
      disable_languages: '["en","ru","zh","ar","fr","de","id","ja","ko","pt","es","sv","tr"]'
      cf_path: "/pdf/*"
      theme_ref: "beta"
    secrets: inherit
