name: Build PUB French Stage

on:
  repository_dispatch:
    types: [ build-pub-french-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-pub/Aspose.PUB-API-References"
      product_name: "pub"
      disable_languages: '["en","ru","zh","ar","de","it","es","sv","tr"]'
      cf_path: "/pub/*"
      theme_ref: "beta"
    secrets: inherit
