name: Build Cells Spanish Stage

on:
  repository_dispatch:
    types: [ build-cells-spanish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-cells/Aspose.Cells-API-References"
      product_name: "cells"
      disable_languages: '["en","ru","zh","ar","fr","de","it","sv","tr"]'
      cf_path: "/cells/es/*"
      theme_ref: "beta"
    secrets: inherit
