name: Build Psd Turkish Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-psd-turkish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-psd/Aspose.PSD-API-References"
      product_name: "psd"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv"]'
      theme_ref: "beta"
    secrets: inherit
