name: Build Words German Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-words-german-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-words/Aspose.Words-API-References"
      product_name: "words"
      disable_languages: '["en","ru","zh","ar","fr","it","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
