name: Build Font Chinese Stage

on:
  repository_dispatch:
    types: [ build-font-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-font/Aspose.Font-API-References"
      product_name: "font"
      disable_languages: '["en","ru","ar","fr","de","it","es","sv","tr"]'
      cf_path: "/font/zh/*"
    secrets: inherit
