name: Build Pdf Chinese Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-pdf-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-pdf/Aspose.PDF-API-References"
      product_name: "pdf"
      disable_languages: '["en","ru","ar","fr","de","id","it","ja","ko","pt","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
