name: Build 3d Netherlands Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-3d-netherlands-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-3d/Aspose.3D-API-References"
      product_name: "3d"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
