name: Build Html Italian Production

on:
  repository_dispatch:
    types: [ build-html-italian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-html/Aspose.HTML-API-References"
      product_name: "html"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","ja","ko","nl","es","sv","tr"]'
      cf_path: "/html/*"
      theme_ref: "beta"
    secrets: inherit
