name: Build Diagram Swedish Stage

on:
  repository_dispatch:
    types: [ build-diagram-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-diagram/Aspose.Diagram-API-References"
      product_name: "diagram"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      cf_path: "/diagram/sv/*"
      theme_ref: "beta"
    secrets: inherit
