name: Build Imaging Turkish Production

on:
  repository_dispatch:
    types: [ build-imaging-turkish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-imaging/Aspose.Imaging-API-References"
      product_name: "imaging"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","sv"]'
      cf_path: "/imaging/*"
      theme_ref: "beta"
    secrets: inherit
