name: Build Pub Russian Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-pub-russian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-pub/Aspose.PUB-API-References"
      product_name: "pub"
      disable_languages: '["en","zh","ar","fr","de","it","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
