name: Build HTML Spanish Stage

on:
  repository_dispatch:
    types: [ build-html-spanish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-html/Aspose.HTML-API-References"
      product_name: "html"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","sv","tr"]'
      cf_path: "/html/*"
      theme_ref: "beta"
    secrets: inherit
