name: Build Ocr Greece Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-ocr-greece-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-ocr/Aspose.OCR-API-References"
      product_name: "ocr"
      disable_languages: '["en","ru","zh","ar","fr","de","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
