name: Build Barcode Indonesian Production

on:
  repository_dispatch:
    types: [ build-barcode-indonesian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-barcode/Aspose.BarCode-API-References"
      product_name: "barcode"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/barcode/id/*"
      theme_ref: "beta"
    secrets: inherit
