name: Build Medical English Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-medical-english-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-medical/Aspose.Medical-API-References"
      product_name: "medical"
      disable_languages: '[]'
      theme_ref: "beta"
    secrets: inherit
