name: Build 3d Indonesian Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-3d-indonesian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-3d/Aspose.3D-API-References"
      product_name: "3d"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
