name: Build Font Swedish Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-font-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-font/Aspose.Font-API-References"
      product_name: "font"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","tr"]'
      theme_ref: "beta"
    secrets: inherit
