name: Build LLM English Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-llm-english-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-llm/Aspose.LLM-References"
      product_name: "llm"
      disable_languages: '[]'
      theme_ref: "beta"
    secrets: inherit
