name: Build Gis Japanese Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-gis-japanese-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-gis/Aspose.GIS-API-Reference"
      product_name: "gis"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
