name: Build Drawing Italian Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-drawing-italian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-drawing/Aspose.Drawing-API-Reference"
      product_name: "drawing"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
