name: Build Ocr English Production

on:
  repository_dispatch:
    types: [ build-ocr-english-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-ocr/Aspose.OCR-API-References"
      product_name: "ocr"
      disable_languages: '["ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/ocr/*"
      theme_ref: "beta"
    secrets: inherit
