name: Build Zip Indonesian Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-zip-indonesian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-zip/Aspose.ZIP-API-References"
      product_name: "zip"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
