name: Build Tasks Swedish Stage

on:
  repository_dispatch:
    types: [ build-tasks-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-tasks/Aspose.Tasks-API-References"
      product_name: "tasks"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      cf_path: "/tasks/*"
      theme_ref: "beta"
    secrets: inherit
