name: Build Svg Japanese Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-svg-japanese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-svg/Aspose.SVG-API-References"
      product_name: "svg"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
