name: Build Ocr Swedish Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-ocr-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-ocr/Aspose.OCR-API-References"
      product_name: "ocr"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      theme_ref: "beta"
    secrets: inherit
