name: Build Diagram German Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-diagram-german-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-diagram/Aspose.Diagram-API-References"
      product_name: "diagram"
      disable_languages: '["en","ru","zh","ar","fr","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
