name: Build Cells Russian Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-cells-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-cells/Aspose.Cells-API-References"
      product_name: "cells"
      disable_languages: '["en","zh","ar","fr","de","it","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
