name: Build Drawing Russian Production

on:
  repository_dispatch:
    types: [ build-drawing-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-drawing/Aspose.Drawing-API-Reference"
      product_name: "drawing"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/drawing/*"
      theme_ref: "beta"
    secrets: inherit
