name: Build Tasks Arabic Production

on:
  repository_dispatch:
    types: [ build-tasks-arabic-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-tasks/Aspose.Tasks-API-References"
      product_name: "tasks"
      disable_languages: '["en","ru","zh","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/tasks/*"
      theme_ref: "beta"
    secrets: inherit
