name: Build OCR Indian Stage

on:
  repository_dispatch:
    types: [ build-ocr-indian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-ocr/Aspose.OCR-API-References"
      product_name: "ocr"
      disable_languages: '["en","ru","zh","ar","fr","de","el","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/ocr/*"
      theme_ref: "beta"
    secrets: inherit
