name: Build PSD Chinese Stage

on:
  repository_dispatch:
    types: [ build-psd-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-psd/Aspose.PSD-API-References"
      product_name: "psd"
      disable_languages: '["en","ru","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/psd/*"
      theme_ref: "beta"
    secrets: inherit
