name: Build Diagram Greece Production

on:
  repository_dispatch:
    types: [ build-diagram-greece-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-diagram/Aspose.Diagram-API-References"
      product_name: "diagram"
      disable_languages: '["en","ru","zh","ar","fr","de","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/diagram/el/*"
      theme_ref: "beta"
    secrets: inherit
