name: Build Barcode Indian Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-barcode-indian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-barcode/Aspose.BarCode-API-References"
      product_name: "barcode"
      disable_languages: '["en","ru","zh","ar","fr","de","el","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
