name: Build Email English Production

on:
  repository_dispatch:
    types: [ build-email-english-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-email/Aspose.Email-API-References"
      product_name: "email"
      disable_languages: '["ru","zh"]'
      cf_path: "/email/*"
      theme_ref: "beta"
    secrets: inherit
