name: Build Imaging Arabic Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-imaging-arabic-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-imaging/Aspose.Imaging-API-References"
      product_name: "imaging"
      disable_languages: '["en","ru","zh","fr","de","it","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
