name: Build Finance English Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-finance-english-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-finance/Aspose.Finance-API-References"
      product_name: "finance"
      disable_languages: '["ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
