name: Build Words Swedish Stage

on:
  repository_dispatch:
    types: [ build-words-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-words/Aspose.Words-API-References"
      product_name: "words"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","tr"]'
      cf_path: "/words/*"
      theme_ref: "beta"
    secrets: inherit
