name: Build Tex Spanish Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-tex-spanish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-tex/Aspose.TeX-API-References"
      product_name: "tex"
      disable_languages: '["en","ru","zh","ar","fr","de","it","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
