name: Build Omr Russian Production

on:
  repository_dispatch:
    types: [ build-omr-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-omr/Aspose.OMR-API-References"
      product_name: "omr"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/omr/*"
      theme_ref: "beta"
    secrets: inherit
