name: Build Page Russian Production

on:
  repository_dispatch:
    types: [ build-page-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-page/Aspose.Page-API-References"
      product_name: "page"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/page/*"
      theme_ref: "beta"
    secrets: inherit
