name: Build Imaging Spanish Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-imaging-spanish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-imaging/Aspose.Imaging-API-References"
      product_name: "imaging"
      disable_languages: '["en","ru","zh","ar","fr","de","it","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
