name: Build Font German Production

on:
  repository_dispatch:
    types: [ build-font-german-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-font/Aspose.Font-API-References"
      product_name: "font"
      disable_languages: '["en","ru","zh","ar","fr","it","es","sv","tr"]'
      cf_path: "/font/de/*"
      theme_ref: "beta"
    secrets: inherit
