name: Build Pub Turkish Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-pub-turkish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-pub/Aspose.PUB-API-References"
      product_name: "pub"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","sv"]'
      theme_ref: "beta"
    secrets: inherit
