name: Build Finance Russian Production

on:
  repository_dispatch:
    types: [ build-finance-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-finance/Aspose.Finance-API-References"
      product_name: "finance"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/finance/*"
      theme_ref: "beta"
    secrets: inherit
