name: Build Omr Chinese Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-omr-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-omr/Aspose.OMR-API-References"
      product_name: "omr"
      disable_languages: '["en","ru","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
