name: Build Barcode French Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-barcode-french-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-barcode/Aspose.BarCode-API-References"
      product_name: "barcode"
      disable_languages: '["en","ru","zh","ar","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
