name: Build Font Spanish Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-font-spanish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-font/Aspose.Font-API-References"
      product_name: "font"
      disable_languages: '["en","ru","zh","ar","fr","de","it","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
