name: Build TeX Turkish Stage

on:
  repository_dispatch:
    types: [ build-tex-turkish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-tex/Aspose.TeX-API-References"
      product_name: "tex"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","sv"]'
      cf_path: "/tex/*"
      theme_ref: "beta"
    secrets: inherit
