name: Build Words English Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-words-english-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-words/Aspose.Words-API-References"
      product_name: "words"
      disable_languages: '["ru","zh","ar","fr","de","it","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
