name: Build Tasks Russian Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-tasks-russian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-tasks/Aspose.Tasks-API-References"
      product_name: "tasks"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
