name: Build Diagram Netherlands Production (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-diagram-netherlands-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production-bunny.yml
    with:
      product_repo: "aspose-diagram/Aspose.Diagram-API-References"
      product_name: "diagram"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
