name: Build Note Indian Production

on:
  repository_dispatch:
    types: [ build-note-indian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-note/Aspose.Note-API-References"
      product_name: "note"
      disable_languages: '["en","ru","zh","ar","fr","de","el","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/note/*"
      theme_ref: "beta"
    secrets: inherit
