name: Build Psd Greece Production

on:
  repository_dispatch:
    types: [ build-psd-greece-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-psd/Aspose.PSD-API-References"
      product_name: "psd"
      disable_languages: '["en","ru","zh","ar","fr","de","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/psd/*"
      theme_ref: "beta"
    secrets: inherit
