name: Build Zip Swedish Production

on:
  repository_dispatch:
    types: [ build-zip-swedish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-zip/Aspose.ZIP-API-References"
      product_name: "zip"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      cf_path: "/zip/*"
      theme_ref: "beta"
    secrets: inherit
