name: Build Note Russian Stage

on:
  repository_dispatch:
    types: [ build-note-russian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-note/Aspose.Note-API-References"
      product_name: "note"
      disable_languages: '["en","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/note/*"
      theme_ref: "beta"
    secrets: inherit
