name: Build Font Italian Stage

on:
  repository_dispatch:
    types: [ build-font-italian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-font/Aspose.Font-API-References"
      product_name: "font"
      disable_languages: '["en","ru","zh","ar","fr","de","es","sv","tr"]'
      cf_path: "/font/it/*"
      theme_ref: "beta"
    secrets: inherit
