name: Build Imaging Chinese Stage

on:
  repository_dispatch:
    types: [ build-imaging-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-imaging/Aspose.Imaging-API-References"
      product_name: "imaging"
      disable_languages: '["en","ru","ar","fr","de","it","es","sv","tr"]'
      cf_path: "/imaging/*"
      theme_ref: "beta"
    secrets: inherit
