name: Build Tex German Production

on:
  repository_dispatch:
    types: [ build-tex-german-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-tex/Aspose.TeX-API-References"
      product_name: "tex"
      disable_languages: '["en","ru","zh","ar","fr","it","es","sv","tr"]'
      cf_path: "/tex/*"
      theme_ref: "beta"
    secrets: inherit
