name: Build GIS Chinese Stage

on:
  repository_dispatch:
    types: [ build-gis-chinese-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-gis/Aspose.GIS-API-Reference"
      product_name: "gis"
      disable_languages: '["en","ru","ar","fr","de","el","hi","id","it","ja","ko","nl","es","sv","tr"]'
      cf_path: "/gis/*"
      theme_ref: "beta"
    secrets: inherit
