name: Build OMR Swedish Stage

on:
  repository_dispatch:
    types: [ build-omr-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-omr/Aspose.OMR-API-References"
      product_name: "omr"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      cf_path: "/omr/*"
      theme_ref: "beta"
    secrets: inherit
