name: Build Psd Indonesian Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-psd-indonesian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-psd/Aspose.PSD-API-References"
      product_name: "psd"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","it","ja","ko","nl","es","sv","tr"]'
      theme_ref: "beta"
    secrets: inherit
