name: Build Zip Italian Production

on:
  repository_dispatch:
    types: [ build-zip-italian-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-zip/Aspose.ZIP-API-References"
      product_name: "zip"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","ja","ko","nl","es","sv","tr"]'
      cf_path: "/zip/*"
      theme_ref: "beta"
    secrets: inherit
