name: Build Gis Swedish Stage (BunnyCDN)

on:
  repository_dispatch:
    types: [ build-gis-swedish-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage-bunny.yml
    with:
      product_repo: "aspose-gis/Aspose.GIS-API-Reference"
      product_name: "gis"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","it","ja","ko","nl","es","tr"]'
      theme_ref: "beta"
    secrets: inherit
