name: Build Cells-python-net Swedish Production

on:
  repository_dispatch:
    types: [ build-cells-python-net-swedish-production ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-production.yml
    with:
      product_repo: "aspose-cells/Aspose.Cells-Python-NET-API-References"
      product_name: "cells-python-net"
      disable_languages: '["en","ru","zh","ar","fr","de","it","es","tr"]'
      cf_path: "/cells/python-net/sv/*"
      theme_ref: "beta"
    secrets: inherit
