name: Build 3D Italian Stage

on:
  repository_dispatch:
    types: [ build-3d-italian-stage ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-stage.yml
    with:
      product_repo: "aspose-3d/Aspose.3D-API-References"
      product_name: "3d"
      disable_languages: '["en","ru","zh","ar","fr","de","el","hi","id","ja","ko","nl","es","sv","tr"]'
      cf_path: "/3d/it/*"
      theme_ref: "beta"
    secrets: inherit
